# Generated by Django 3.2.22 on 2024-01-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=20)),
                ('stock_symbol', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('revenue_growth_rate', models.CharField(max_length=10)),
                ('pre_tax_op_margin', models.CharField(max_length=10)),
                ('pre_tax_op_income', models.CharField(max_length=10)),
                ('taxes', models.FloatField()),
                ('after_tax_op_income', models.FloatField()),
                ('taxes_val', models.FloatField()),
                ('chge_revenues', models.CharField(max_length=10)),
                ('sales_to_capital', models.FloatField()),
                ('reinvestment', models.FloatField()),
                ('fcff', models.FloatField()),
                ('invested_capital', models.FloatField()),
                ('implied_roic', models.FloatField()),
                ('cost_of_capital', models.FloatField()),
                ('cum_cost_of_capital', models.FloatField()),
                ('preset_value', models.FloatField()),
                ('period', models.ManyToManyField(to='csv_app.Period')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financialdata', to='csv_app.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(max_length=200, upload_to='csvs/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
                ('period', models.ManyToManyField(to='csv_app.Period')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv', to='csv_app.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('period', models.ManyToManyField(to='csv_app.Period')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='csv_app.stock')),
            ],
        ),
    ]
