# Generated by Django 3.2.22 on 2024-01-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0002_auto_20240124_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata',
            name='pre_tax_op_margin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='revenue_growth_rate',
            field=models.FloatField(),
        ),
    ]
